---
substitutions:
  device_name: "shellystudy"
  friendly_name: "Shelly Light Switch Study"
  area: "study"
  light1_icon: "mdi:chandelier"
  device_ip: "11"
  ssid: !secret "not_wifi_ssid"
  log_level: "DEBUG"
  max_temp: "80.0"  # Centigrade

# Common Include
<<: !include "includes/shelly_1l_common.yaml"

# Extended Config - only use when overwriting values in include
# Note: the entire light and binary_sensor blocks will be overwritten
